// Registro dos Web Components via defineCustomElement individual (aplica os estilos do shadow).
// O barrel dist/components/index.js (auto-define) NÃO aplica estilos — por isso registramos um a um.
import { defineCustomElement as def0 } from "@andespindola/ui-core/dist/components/ui-accordion.js";
import { defineCustomElement as def1 } from "@andespindola/ui-core/dist/components/ui-accordion-item.js";
import { defineCustomElement as def2 } from "@andespindola/ui-core/dist/components/ui-avatar.js";
import { defineCustomElement as def3 } from "@andespindola/ui-core/dist/components/ui-badge.js";
import { defineCustomElement as def4 } from "@andespindola/ui-core/dist/components/ui-button.js";
import { defineCustomElement as def5 } from "@andespindola/ui-core/dist/components/ui-card.js";
import { defineCustomElement as def6 } from "@andespindola/ui-core/dist/components/ui-checkbox.js";
import { defineCustomElement as def7 } from "@andespindola/ui-core/dist/components/ui-dialog.js";
import { defineCustomElement as def8 } from "@andespindola/ui-core/dist/components/ui-drawer.js";
import { defineCustomElement as def9 } from "@andespindola/ui-core/dist/components/ui-dropdown-item.js";
import { defineCustomElement as def10 } from "@andespindola/ui-core/dist/components/ui-dropdown-menu.js";
import { defineCustomElement as def11 } from "@andespindola/ui-core/dist/components/ui-field.js";
import { defineCustomElement as def12 } from "@andespindola/ui-core/dist/components/ui-input.js";
import { defineCustomElement as def13 } from "@andespindola/ui-core/dist/components/ui-label.js";
import { defineCustomElement as def14 } from "@andespindola/ui-core/dist/components/ui-loading-overlay.js";
import { defineCustomElement as def15 } from "@andespindola/ui-core/dist/components/ui-popover.js";
import { defineCustomElement as def16 } from "@andespindola/ui-core/dist/components/ui-progress.js";
import { defineCustomElement as def17 } from "@andespindola/ui-core/dist/components/ui-radio-group.js";
import { defineCustomElement as def18 } from "@andespindola/ui-core/dist/components/ui-reveal.js";
import { defineCustomElement as def19 } from "@andespindola/ui-core/dist/components/ui-scroll-progress.js";
import { defineCustomElement as def20 } from "@andespindola/ui-core/dist/components/ui-section.js";
import { defineCustomElement as def21 } from "@andespindola/ui-core/dist/components/ui-select.js";
import { defineCustomElement as def22 } from "@andespindola/ui-core/dist/components/ui-separator.js";
import { defineCustomElement as def23 } from "@andespindola/ui-core/dist/components/ui-skeleton.js";
import { defineCustomElement as def24 } from "@andespindola/ui-core/dist/components/ui-slider.js";
import { defineCustomElement as def25 } from "@andespindola/ui-core/dist/components/ui-spinner.js";
import { defineCustomElement as def26 } from "@andespindola/ui-core/dist/components/ui-switch.js";
import { defineCustomElement as def27 } from "@andespindola/ui-core/dist/components/ui-tabs.js";
import { defineCustomElement as def28 } from "@andespindola/ui-core/dist/components/ui-textarea.js";
import { defineCustomElement as def29 } from "@andespindola/ui-core/dist/components/ui-theme-toggle.js";
import { defineCustomElement as def30 } from "@andespindola/ui-core/dist/components/ui-toast.js";
import { defineCustomElement as def31 } from "@andespindola/ui-core/dist/components/ui-toaster.js";
import { defineCustomElement as def32 } from "@andespindola/ui-core/dist/components/ui-tooltip.js";

def0();
def1();
def2();
def3();
def4();
def5();
def6();
def7();
def8();
def9();
def10();
def11();
def12();
def13();
def14();
def15();
def16();
def17();
def18();
def19();
def20();
def21();
def22();
def23();
def24();
def25();
def26();
def27();
def28();
def29();
def30();
def31();
def32();
