// Registra os Web Components via defineCustomElement individual (estilos do shadow aplicados).
import { defineCustomElement as def0 } from "../../core/dist/components/ui-accordion.js";
import { defineCustomElement as def1 } from "../../core/dist/components/ui-accordion-item.js";
import { defineCustomElement as def2 } from "../../core/dist/components/ui-alert.js";
import { defineCustomElement as def3 } from "../../core/dist/components/ui-avatar.js";
import { defineCustomElement as def4 } from "../../core/dist/components/ui-avatar-group.js";
import { defineCustomElement as def5 } from "../../core/dist/components/ui-badge.js";
import { defineCustomElement as def6 } from "../../core/dist/components/ui-breadcrumb.js";
import { defineCustomElement as def7 } from "../../core/dist/components/ui-breadcrumb-item.js";
import { defineCustomElement as def8 } from "../../core/dist/components/ui-button.js";
import { defineCustomElement as def9 } from "../../core/dist/components/ui-card.js";
import { defineCustomElement as def10 } from "../../core/dist/components/ui-carousel.js";
import { defineCustomElement as def11 } from "../../core/dist/components/ui-checkbox.js";
import { defineCustomElement as def12 } from "../../core/dist/components/ui-combobox.js";
import { defineCustomElement as def13 } from "../../core/dist/components/ui-command.js";
import { defineCustomElement as def14 } from "../../core/dist/components/ui-container.js";
import { defineCustomElement as def15 } from "../../core/dist/components/ui-date-picker.js";
import { defineCustomElement as def16 } from "../../core/dist/components/ui-dialog.js";
import { defineCustomElement as def17 } from "../../core/dist/components/ui-drawer.js";
import { defineCustomElement as def18 } from "../../core/dist/components/ui-dropdown-item.js";
import { defineCustomElement as def19 } from "../../core/dist/components/ui-dropdown-menu.js";
import { defineCustomElement as def20 } from "../../core/dist/components/ui-field.js";
import { defineCustomElement as def21 } from "../../core/dist/components/ui-file-upload.js";
import { defineCustomElement as def22 } from "../../core/dist/components/ui-grid.js";
import { defineCustomElement as def23 } from "../../core/dist/components/ui-input.js";
import { defineCustomElement as def24 } from "../../core/dist/components/ui-label.js";
import { defineCustomElement as def25 } from "../../core/dist/components/ui-loading-overlay.js";
import { defineCustomElement as def26 } from "../../core/dist/components/ui-navbar.js";
import { defineCustomElement as def27 } from "../../core/dist/components/ui-pagination.js";
import { defineCustomElement as def28 } from "../../core/dist/components/ui-popover.js";
import { defineCustomElement as def29 } from "../../core/dist/components/ui-progress.js";
import { defineCustomElement as def30 } from "../../core/dist/components/ui-progress-circular.js";
import { defineCustomElement as def31 } from "../../core/dist/components/ui-radio-group.js";
import { defineCustomElement as def32 } from "../../core/dist/components/ui-rating.js";
import { defineCustomElement as def33 } from "../../core/dist/components/ui-reveal.js";
import { defineCustomElement as def34 } from "../../core/dist/components/ui-scroll-progress.js";
import { defineCustomElement as def35 } from "../../core/dist/components/ui-section.js";
import { defineCustomElement as def36 } from "../../core/dist/components/ui-segmented.js";
import { defineCustomElement as def37 } from "../../core/dist/components/ui-select.js";
import { defineCustomElement as def38 } from "../../core/dist/components/ui-separator.js";
import { defineCustomElement as def39 } from "../../core/dist/components/ui-skeleton.js";
import { defineCustomElement as def40 } from "../../core/dist/components/ui-slider.js";
import { defineCustomElement as def41 } from "../../core/dist/components/ui-spinner.js";
import { defineCustomElement as def42 } from "../../core/dist/components/ui-stack.js";
import { defineCustomElement as def43 } from "../../core/dist/components/ui-stat.js";
import { defineCustomElement as def44 } from "../../core/dist/components/ui-switch.js";
import { defineCustomElement as def45 } from "../../core/dist/components/ui-table.js";
import { defineCustomElement as def46 } from "../../core/dist/components/ui-tabs.js";
import { defineCustomElement as def47 } from "../../core/dist/components/ui-textarea.js";
import { defineCustomElement as def48 } from "../../core/dist/components/ui-theme-toggle.js";
import { defineCustomElement as def49 } from "../../core/dist/components/ui-timeline.js";
import { defineCustomElement as def50 } from "../../core/dist/components/ui-timeline-item.js";
import { defineCustomElement as def51 } from "../../core/dist/components/ui-toast.js";
import { defineCustomElement as def52 } from "../../core/dist/components/ui-toaster.js";
import { defineCustomElement as def53 } from "../../core/dist/components/ui-tooltip.js";

def0();
def1();
def2();
def3();
def4();
def5();
def6();
def7();
def8();
def9();
def10();
def11();
def12();
def13();
def14();
def15();
def16();
def17();
def18();
def19();
def20();
def21();
def22();
def23();
def24();
def25();
def26();
def27();
def28();
def29();
def30();
def31();
def32();
def33();
def34();
def35();
def36();
def37();
def38();
def39();
def40();
def41();
def42();
def43();
def44();
def45();
def46();
def47();
def48();
def49();
def50();
def51();
def52();
def53();
